config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: 'pages#home'
  devise_for :users
  devise_scope :user do
  get '/users/sign_out' => 'devise/sessions#destroy'
  post '/buy/:slug', to: 'transactions#create', as: :buy
  get '/pickup/:uuid', to: 'transactions#pickup', as: :pickup  
  get 'dashboard' => 'pages#dashboard'
	end
  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      can :read, :all
      can :manage, Book do |book|
        book.try(:user) == user
    end
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	extend FriendlyId
  	friendly_id :name, use: :slugged
	

	belongs_to :user
	has_many :sale
	has_attached_file :image
	has_attached_file :resource 
	#each book will have two file attachments which is image and resource
	validates_attachment :image, presence: true,
	content_type: { content_type: ["image/jpeg", "image/gif", "image/png", "image/jpg"] },
	message: 'Only images allowed'


	validates_attachment  :resource,presence: true, 
	content_type: { content_type: "application/pdf" },
	message: 'only pdf allowed'


	validates_numericality_of :price,
	greater_than: 49, message: "Price must be greater than 50"
end

app/models/sale.rb
class Sale < ApplicationRecord
	belongs_to :book
	before_create :populate_uuid 
	# before it creates a sale it will generate an id to that sale 

	include AASM

	aasm column: 'state' do 
		state :pending, :initial => true
		state :processing
		state :finished
		state :failure

		event :process, after: :charge_card do
			transitions from:   :pending, to: :processing
    	end

    	event :finish do
    		transitions from:   :processing, to: :finished
    	end

    	event :fail do
    		transitions from:  :finished, to: :failure
    	end
	end

	def charge_card
		begin
			save!
			charge = Stripe::Charge.create(
				amount:      self.amount,
				currency:      "usd",
		 	    card:        self.stripe_token,
		 	    description:  "Book Sale",
			     
				)

			self.update(stripe_id: charge.id)
			self.finish!
		rescue Stripe::StripeError => e
			self.update_atrributes(error: e.message)
			self.fail!
		end
	end

	private

	def populate_uuid

		self.uuid = SecureRandom.uuid()
	end
end

app/models/user.rb
class User < ApplicationRecord
   
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	rescue_from CanCan::AccessDenied do |exception|
	redirect_to root_path, notice: "You are not authorized to access this page" 
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  # GET /books
  # GET /books.json
  def index
    @books = Book.all.where(availability: true)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    authorize! :manage, @book
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    authorize! :manage, @book
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    authorize! :manage, @book
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :price, :availability, :image, :resource)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	before_action :authenticate_user! , only: [:dashboard]
  def home
  	if current_user
  		redirect_to books_path
  	end
  	@books = Book.all
  end

  def dashboard
  	@books = current_user.books
    @purchased = Sale.where(buyer_email: current_user.email)
    @sales = Sale.where(seller_email: current_user.email)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
#needs two methods
def create
	book = Book.find_by!(slug: params[:slug])
	sale = book.sale.create(
		amount: book.price,
		buyer_email: current_user.email,
		seller_email: book.user.email,
		stripe_token: params[:stripeToken])
	sale.process!
	
	if sale.finished?
		redirect_to pickup_url(uuid: sale.uuid)
	else
		  redirect_to book_path(book), notice: e.message
	end
end

def pickup
	@sale = Sale.find_by!(uuid: params[:uuid])
	@book = @sale.book
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_book.html.erb
<div class="col-3">
  <div class="thumbnail">
    <%= image_tag book.image.url, class: 'img-fluid fluid-1 '%>
  </div>
  <div class="caption">
  <p>
    <strong><%= link_to book.name, book_path(book) %></strong></p>
<p class="p-money">$<%= book.price/100 %></p>
  </div>
</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book, html: {class: "form-signin"}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, required: true, label: false, placeholder: "Name" %>
    <%= f.input :author, required: true, label: false, placeholder: "Author" %>
    <%= f.input :description, required: true, label: false, placeholder: "Book Description" %>
     
    <%= f.input :image %>
    <%= f.input :resource %>
    <%= f.input :price, required: true, label: false, placeholder: "Price" %>
    <%= f.input :availability %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-warning " %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1 class="text-center">Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="row">
  
 <%= render @books %>

 
</div>



<br>

<%= link_to 'New Book', new_book_path, class: "btn btn-outline-warning" %>

app/views/books/new.html.erb
<h1 class="text-center">New Book</h1>

<%= render 'form', book: @book %>

app/views/books/show.html.erb
<div class="row">
	
	<div class="col-6">
		<%= image_tag @book.image.url, class: 'img-fluid', style: 'height: 470px;width:350px;'%>
	</div>
	<div class="col-6">
		<h3><%= @book.name %> by <%= @book.author %></h3>
		<br>
		<p>
			<%= @book.description %>
		</p>
		<br>
		<h3 class="text-center">Book Price: $<%= @book.price/100 %></h3>
<% if current_user %>
	<%= form_tag buy_path(slug: @book.slug) do %>
		<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
		data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
		data-description="<%= @book.name %>"
		data-name="ebook"
		data-amount="<%= @book.price %>"
		data-email="<%= current_user.email %>"
		data-locale="auto"></script>
	<% end %>
	<div class="container">
		<hr>
<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>
</div>
	<% else %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
	<p class="text-center">Log in to buy this book. Please use this email --> test@test.com , password --> aloha01 to try out the app. Thank you!</p>
</div>
	<% end %>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <%= render 'partials/navbar'%>
    <br>
    <% flash.each do |type, message|%>
    <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <%= message %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/pages/dashboard.html.erb
<h2 class="dashboard-h1">User: <%= current_user.email %>
<%= link_to 'New Book', new_book_path, class: 'btn btn-warning' %></h2>
<div class="row">
	
	<div class="col-md-4">
		<h3>Books 
</h3>
		 <%= render 'partials/books' %>
	</div>
	<div class="col-md-4">
		<h3>Purchases</h3>
		<%= render 'partials/purchased' %>
	</div>
	<div class="col-md-4">
		<h3>Sales</h3>
		<%= render 'partials/sales' %>
	</div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron">
	  <h1 class="display-4">Welcome to ebook</h1>
  <p class="lead">Buy and sell your ebook startup</p>
  <%= link_to 'Books', books_path, class: 'btn btn-warning btn-lg' %>
  <%= link_to 'Sign Up', new_user_registration_path, class: 'btn btn-info btn-lg' %>

</div>

<div class="row">
	<%=  render @books %>
</div>

app/views/partials/_books.html.erb
<table class="table">
			<thead>
				<tr>
					<th scope="col">ID</th>
					<th scope="col">Name</th>
					<th scope="col">Availability</th>
					<th scope="col"></th>
				</tr>
			</thead>
			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td><%= book.id %></td>
					<td><%= link_to book.name, book_path(book) %></td>
					<td><%= book.availability %></td>
					<td><%= link_to 'Edit', edit_book_path(book) %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-light" style="background-color: black;">
  <div class="container-fluid">
    
    
    
    <%= link_to '<i class="fa fa-chain-broken" aria-hidden="true" style="color: white; font-size: 2.1rem"></i>'.html_safe, root_path %>
      
      <div class="navbar-item">

         <ul class="">
         <li><%= link_to 'books', books_path %></li>
        <% if user_signed_in? %>
        
          <li><%= link_to 'Dashboard', dashboard_path %></li>
          <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
          <% else %>
          <!-- // profile edit and logout else do  -->
          
          <li><%= link_to 'Log in', new_user_session_path %></li>
          
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
          
        </ul>
        <% end %>
      </div>
    
  </div>
</nav>

app/views/partials/_purchased.html.erb
<table class="table">
			<thead>
				<tr>
					<th scope="col">Name</th>
					<th scope="col">Date</th>
				</tr>
			</thead>
			<tbody>
				<% @purchased.each do |sale| %>
				<tr>
					<td><%= link_to sale.book.name, pickup_path(sale.uuid) %></td>
					<td><%= time_ago_in_words(sale.created_at) %> ago</td>
				</tr>
				<% end %>
			</tbody>
		</table>

app/views/partials/_sales.html.erb
<table class="table">
			<thead>
				<tr>
					<th scope="col">Name</th>
					<th scope="col">Date</th>
					<th scope="col">Buyer</th>
				</tr>
			</thead>
			<tbody>
				<% @sales.each do |sale| %>
				<tr>
					<td><%= link_to sale.book.name, pickup_path(sale.uuid) %></td>
					<td><%= time_ago_in_words(sale.created_at) %> ago</td>
					<td><%= sale.buyer_email %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

app/views/transactions/pickup.html.erb
<div class="row text-center", style="display: block;">
	<h1>Congratulations!</h1>
	<h3>Here is the <%= link_to 'download', @book.resource.url %> to your book </h3>
</div>